/* eslint-disable */
// Auto-generated by scripts/generate-client-logos.mjs
// Do not edit manually.

export const clientLogos = [
  {
    "src": "/media/logos/clients/fairway.logo.svg",
    "alt": "Fairway logo"
  },
  {
    "src": "/media/logos/clients/logo.brdr.price.svg",
    "alt": "Logo Brdr Price logo"
  },
  {
    "src": "/media/logos/clients/logo.rigshospitalet.png",
    "alt": "Logo Rigshospitalet logo"
  },
  {
    "src": "/media/logos/clients/logo.sengeloesekro.svg",
    "alt": "Logo Sengeloesekro logo"
  },
  {
    "src": "/media/logos/clients/logo.skatteministeriet.svg",
    "alt": "Logo Skatteministeriet logo"
  },
  {
    "src": "/media/logos/clients/logo.vibenshuset.svg",
    "alt": "Logo Vibenshuset logo"
  }
] as const;

