/* eslint-disable */
// Auto-generated by scripts/generate-enterprise-cases.mjs
// Do not edit manually.

export type EnterpriseCase = {
  id: string;
  clientId: string;
  clientName: string;
  clientLogoSrc?: string;
  title: string;
  coverSrc: string;
  imageSrcs: string[];
};

export const enterpriseCases: EnterpriseCase[] = [
  {
    "id": "case-001:vibenshuset",
    "clientId": "case-001:vibenshuset",
    "clientName": "Vibenshuset",
    "clientLogoSrc": "/media/logos/clients/logo.vibenshuset.svg",
    "title": "Opgave for Vibenshuset",
    "coverSrc": "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A12-after.JPG",
    "imageSrcs": [
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A01-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A01-before.JPG",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A02-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A02-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A03-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A03-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A04-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A04-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A05-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A05-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A06-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A07-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A07-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A08-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A08-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A09-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A09-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A10-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A10-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A11-after.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A11-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A12-after.JPG",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A12-before.jpg",
      "/media/cases/enterprise/case-001%3Avibenshuset/vibenhus%3Acase-001%3A13-before.jpg"
    ]
  },
  {
    "id": "case-002:brdr.price.tivoli",
    "clientId": "case-002:brdr.price.tivoli",
    "clientName": "Brdr Price Tivoli",
    "clientLogoSrc": "/media/logos/clients/logo.brdr.price.svg",
    "title": "Opgave for Brdr Price Tivoli",
    "coverSrc": "/media/cases/enterprise/case-002%3Abrdr.price.tivoli/brdr.price%3Acase-002%3A02-after.jpg",
    "imageSrcs": [
      "/media/cases/enterprise/case-002%3Abrdr.price.tivoli/brdr.price%3Acase-002%3A01-after.JPG",
      "/media/cases/enterprise/case-002%3Abrdr.price.tivoli/brdr.price%3Acase-002%3A01-before.jpg",
      "/media/cases/enterprise/case-002%3Abrdr.price.tivoli/brdr.price%3Acase-002%3A02-after.jpg",
      "/media/cases/enterprise/case-002%3Abrdr.price.tivoli/brdr.price%3Acase-002%3A02-before..JPG",
      "/media/cases/enterprise/case-002%3Abrdr.price.tivoli/brdr.price%3Acase-002%3A03-after.jpg",
      "/media/cases/enterprise/case-002%3Abrdr.price.tivoli/brdr.price%3Acase-002%3A04-after.jpg"
    ]
  },
  {
    "id": "case-003:fairway",
    "clientId": "case-003:fairway",
    "clientName": "Fairway",
    "clientLogoSrc": "/media/logos/clients/fairway.logo.svg",
    "title": "Opgave for Fairway",
    "coverSrc": "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A03-after.jpg",
    "imageSrcs": [
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A01-after.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A01-before.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A02-after.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A02-before.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A03-after.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A03-before.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A04-after.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A05-after.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A05-before.jpg",
      "/media/cases/enterprise/case-003%3Afairway/fairway%3Acase-004%3A06-before.jpg"
    ]
  },
  {
    "id": "case-004:sengeloese-kro",
    "clientId": "case-004:sengeloese-kro",
    "clientName": "Sengeloese Kro",
    "clientLogoSrc": "/media/logos/clients/logo.sengeloesekro.svg",
    "title": "Opgave for Sengeloese Kro",
    "coverSrc": "/media/cases/enterprise/case-004%3Asengeloese-kro/sengeloese-kro%3Acase-003%3A01-after.jpg",
    "imageSrcs": [
      "/media/cases/enterprise/case-004%3Asengeloese-kro/sengeloese-kro%3Acase-003%3A01-after.jpg",
      "/media/cases/enterprise/case-004%3Asengeloese-kro/sengeloese-kro%3Acase-003%3A01-before..jpg",
      "/media/cases/enterprise/case-004%3Asengeloese-kro/sengeloese-kro%3Acase-003%3A02-after.jpg",
      "/media/cases/enterprise/case-004%3Asengeloese-kro/sengeloese-kro%3Acase-003%3A02-before.jpg"
    ]
  },
  {
    "id": "case-005:skatteministeriet",
    "clientId": "case-005:skatteministeriet",
    "clientName": "Skatteministeriet",
    "clientLogoSrc": "/media/logos/clients/logo.skatteministeriet.svg",
    "title": "Opgave for Skatteministeriet",
    "coverSrc": "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A07-afte.jpg",
    "imageSrcs": [
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A01-after.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A01-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A02-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A02-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A03-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A03-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A04-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A04-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A05-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A05-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A06-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A06-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A07-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A07-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A08-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A08-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A09-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A09-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A10-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A10-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A11-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A11-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A12-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A12-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A13-afte.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A13-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A14-afte.JPG",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A14-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A15-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A16-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A17-before.jpg",
      "/media/cases/enterprise/case-005%3Askatteministeriet/skatteministeriet%3Acase-005%3A18-before.jpg"
    ]
  },
  {
    "id": "case-006:rigshospitalets.patienthotel",
    "clientId": "case-006:rigshospitalets.patienthotel",
    "clientName": "Rigshospitalets Patienthotel",
    "clientLogoSrc": "/media/logos/clients/logo.rigshospitalet.png",
    "title": "Opgave for Rigshospitalets Patienthotel",
    "coverSrc": "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A02-after..jpg",
    "imageSrcs": [
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A01-after.jpg",
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A01-before.jpg",
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A02-after..jpg",
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A02-before.jpg",
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A03-after..jpg",
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A03-before.jpg",
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A04-after..jpg",
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A05-after..jpg",
      "/media/cases/enterprise/case-006%3Arigshospitalets.patienthotel/rigshospitalets-patienthotel%3Acase-006%3A07-before.JPG"
    ]
  }
];

