/* eslint-disable */
// Auto-generated by scripts/generate-media-manifest.mjs
// Do not edit manually.

export type BeforeAfterItem = {
  caseId: string;
  beforeSrc: string;
  afterSrc: string;
};

export type CasesManifestCategory = "bordplade" | "gulvafslibning" | "gulvbelaegning";

export type CasesManifestItem = {
  id: string;
  caseId: string;
  category: CasesManifestCategory;
  frontSrc: string | null;
  beforeSrc: string | null;
  afterSrc: string | null;
  gallery: string[];
  title: string;
  location: string | null;
  clientLogoSrc?: string;
};

export const beforeAfterGulv: BeforeAfterItem[] = [
  {
    "caseId": "case-001_stairs",
    "beforeSrc": "/media/galleries:gulv:before-after/case-001_stairs/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-001_stairs/after.01.jpg"
  },
  {
    "caseId": "case-002_dark_wood",
    "beforeSrc": "/media/galleries:gulv:before-after/case-002_dark_wood/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-002_dark_wood/after.01.jpg"
  },
  {
    "caseId": "case-002_Plankegulv_hvid_lud",
    "beforeSrc": "/media/cases:gulv/case-002_Plankegulv_hvid_lud/before.1.jpg",
    "afterSrc": "/media/cases:gulv/case-002_Plankegulv_hvid_lud/after.1.jpg"
  },
  {
    "caseId": "case-003_fyrtrae",
    "beforeSrc": "/media/galleries:gulv:before-after/case-003_fyrtrae/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-003_fyrtrae/after.01.jpg"
  },
  {
    "caseId": "case-003_Plankegulv_Hvid_lud",
    "beforeSrc": "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/before.1.jpg",
    "afterSrc": "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/after:front.jpg"
  },
  {
    "caseId": "case-004_fernis",
    "beforeSrc": "/media/galleries:gulv:before-after/case-004_fernis/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-004_fernis/after.01.jpg"
  },
  {
    "caseId": "case-004_Sildeben_natur_olie",
    "beforeSrc": "/media/cases:gulv/case-004_Sildeben_natur_olie/before.1.JPG",
    "afterSrc": "/media/cases:gulv/case-004_Sildeben_natur_olie/after.1.jpg"
  },
  {
    "caseId": "case-005_fernis_stairs",
    "beforeSrc": "/media/galleries:gulv:before-after/case-005_fernis_stairs/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-005_fernis_stairs/after.01.jpg"
  },
  {
    "caseId": "case-006_old",
    "beforeSrc": "/media/galleries:gulv:before-after/case-006_old/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-006_old/after.01.jpg"
  },
  {
    "caseId": "case-007_fyrtrae",
    "beforeSrc": "/media/galleries:gulv:before-after/case-007_fyrtrae/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-007_fyrtrae/after.01.jpg"
  }
];

export const beforeAfterBordplade: BeforeAfterItem[] = [
  {
    "caseId": "case_002_koekken_boeg_hvid_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case_002_koekken_boeg_hvid_olie/case-005_koekken_before_boeg_hvid_olie.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case_002_koekken_boeg_hvid_olie/case-005_koekken_after_boeg_hvid_olie.jpeg"
  },
  {
    "caseId": "case-001_koekken_egetrae_hvid_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-001_koekken_egetrae_hvid_olie/before.jpg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-001_koekken_egetrae_hvid_olie/after.jpg"
  },
  {
    "caseId": "case-002_koekken__valnoed_natur_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-002_koekken__valnoed_natur_olie/case-002_koekken_before.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-002_koekken__valnoed_natur_olie/case-002_koekken_after.jpeg"
  },
  {
    "caseId": "case-003_koekken_gummitrae_hvid_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-003_koekken_gummitrae_hvid_olie/case-003_koekken_before.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-003_koekken_gummitrae_hvid_olie/case-003_koekken_after.jpeg"
  },
  {
    "caseId": "case-003_valnoed_natur_olie",
    "beforeSrc": "/media/cases:bordplade/case-003_valnoed_natur_olie/before.1.JPG",
    "afterSrc": "/media/cases:bordplade/case-003_valnoed_natur_olie/after.1.jpeg"
  },
  {
    "caseId": "case-004_egetrae_hvid_olie",
    "beforeSrc": "/media/cases:bordplade/case-004_egetrae_hvid_olie/before.2.JPG",
    "afterSrc": "/media/cases:bordplade/case-004_egetrae_hvid_olie/after.2.JPG"
  },
  {
    "caseId": "case-004_koekken_egetrae_hvid_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-004_koekken_egetrae_hvid_olie/case-004_koekken_before.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-004_koekken_egetrae_hvid_olie/case-004_koekken_after.jpeg"
  },
  {
    "caseId": "case-005_egetrae_natur_olie",
    "beforeSrc": "/media/cases:bordplade/case-005_egetrae_natur_olie/before.1.jpeg",
    "afterSrc": "/media/cases:bordplade/case-005_egetrae_natur_olie/after.1.jpeg"
  },
  {
    "caseId": "case-006_gummitrae_hvid_olie",
    "beforeSrc": "/media/cases:bordplade/case-006_gummitrae_hvid_olie/before.1.JPG",
    "afterSrc": "/media/cases:bordplade/case-006_gummitrae_hvid_olie/after.1.JPG"
  },
  {
    "caseId": "case-006_koekken_valnoed_natur_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-006_koekken_valnoed_natur_olie/Before..jpg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-006_koekken_valnoed_natur_olie/after..jpg"
  },
  {
    "caseId": "case-007_valnoed_natur_olie",
    "beforeSrc": "/media/cases:bordplade/case-007_valnoed_natur_olie/before.1.jpeg",
    "afterSrc": "/media/cases:bordplade/case-007_valnoed_natur_olie/after.1.jpeg"
  },
  {
    "caseId": "case-008_koekken_ask_hvid_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-008_koekken_ask_hvid_olie/before..jpg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-008_koekken_ask_hvid_olie/after..jpg"
  },
  {
    "caseId": "case-009_spisebord_teak_natur_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-009_spisebord_teak_natur_olie/before.jpg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-009_spisebord_teak_natur_olie/after.jpg"
  },
  {
    "caseId": "case-010_koekken_valnoed_natur_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-010_koekken_valnoed_natur_olie/before.JPG",
    "afterSrc": "/media/galleries:bordplade:before-after/case-010_koekken_valnoed_natur_olie/after.jpeg"
  },
  {
    "caseId": "case-011_koekken_mahogni_natur_olie",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-011_koekken_mahogni_natur_olie/before.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-011_koekken_mahogni_natur_olie/after.jpeg"
  }
];

export const galleryGulv: string[] = [
  "/media/featured:gulv/2.JPG",
  "/media/featured:gulv/3.JPG",
  "/media/featured:gulv/4.jpg",
  "/media/featured:gulv/20221212_111817.jpg",
  "/media/featured:gulv/20221212_111845.jpg",
  "/media/featured:gulv/20230219_193820.jpg",
  "/media/featured:gulv/20230311_122438.jpg",
  "/media/featured:gulv/FB_IMG_1668201336587.jpg",
  "/media/featured:gulv/feature.1.jpg",
  "/media/featured:gulv/feature.2.jpeg",
  "/media/featured:gulv/feature3.JPG",
  "/media/featured:gulv/header.jpg",
  "/media/featured:gulv/received_583538716870503.jpeg"
];

export const galleryBordplade: string[] = [
  "/media/featured:bordplade/20210302_093123.jpg",
  "/media/featured:bordplade/20210302_160950.jpg",
  "/media/featured:bordplade/20210308_105216.jpg",
  "/media/featured:bordplade/20210320_105853.jpg",
  "/media/featured:bordplade/1000000214.JPG",
  "/media/featured:bordplade/IMG_3383 3.jpeg",
  "/media/featured:bordplade/IMG_3602.jpeg",
  "/media/featured:bordplade/IMG_3737 3.jpeg"
];

export const galleryGulvbelaegning: string[] = [
  "/media/featured:gulvbelaegning/1000000297.JPG",
  "/media/featured:gulvbelaegning/1000000507.JPG",
  "/media/featured:gulvbelaegning/1000000509.JPG",
  "/media/featured:gulvbelaegning/1000000512.JPG"
];

export const casesManifest: CasesManifestItem[] = [
  {
    "id": "bordplade:case_002_koekken_boeg_hvid_olie",
    "caseId": "case_002_koekken_boeg_hvid_olie",
    "category": "bordplade",
    "title": "Køkken Bøg Hvid Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case_002_koekken_boeg_hvid_olie/case-005_koekken_before_boeg_hvid_olie.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case_002_koekken_boeg_hvid_olie/case-005_koekken_after_boeg_hvid_olie.jpeg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case_002_koekken_boeg_hvid_olie/case-005_koekken_after_boeg_hvid_olie.jpeg",
      "/media/galleries:bordplade:before-after/case_002_koekken_boeg_hvid_olie/case-005_koekken_before_boeg_hvid_olie.jpeg"
    ]
  },
  {
    "id": "bordplade:case-001_egetræ_natur_olie",
    "caseId": "case-001_egetræ_natur_olie",
    "category": "bordplade",
    "title": "Egetræ Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": null,
    "afterSrc": "/media/cases:bordplade/case-001_egetræ_natur_olie/after.1.JPG",
    "gallery": [
      "/media/cases:bordplade/case-001_egetræ_natur_olie/after.1.JPG",
      "/media/cases:bordplade/case-001_egetræ_natur_olie/after.2.JPG"
    ]
  },
  {
    "id": "bordplade:case-001_koekken_egetrae_hvid_olie",
    "caseId": "case-001_koekken_egetrae_hvid_olie",
    "category": "bordplade",
    "title": "Køkken Egetræ Hvid Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-001_koekken_egetrae_hvid_olie/before.jpg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-001_koekken_egetrae_hvid_olie/after.jpg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-001_koekken_egetrae_hvid_olie/after.jpg",
      "/media/galleries:bordplade:before-after/case-001_koekken_egetrae_hvid_olie/before.jpg"
    ]
  },
  {
    "id": "bordplade:case-002_egetræ_natur_olie",
    "caseId": "case-002_egetræ_natur_olie",
    "category": "bordplade",
    "title": "Egetræ Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": null,
    "afterSrc": "/media/cases:bordplade/case-002_egetræ_natur_olie/after.1.JPG",
    "gallery": [
      "/media/cases:bordplade/case-002_egetræ_natur_olie/after.1.JPG",
      "/media/cases:bordplade/case-002_egetræ_natur_olie/after.2.JPG"
    ]
  },
  {
    "id": "bordplade:case-002_koekken__valnoed_natur_olie",
    "caseId": "case-002_koekken__valnoed_natur_olie",
    "category": "bordplade",
    "title": "Køkken Valnød Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-002_koekken__valnoed_natur_olie/case-002_koekken_before.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-002_koekken__valnoed_natur_olie/case-002_koekken_after.jpeg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-002_koekken__valnoed_natur_olie/case-002_koekken_after.jpeg",
      "/media/galleries:bordplade:before-after/case-002_koekken__valnoed_natur_olie/case-002_koekken_before.jpeg"
    ]
  },
  {
    "id": "bordplade:case-003_koekken_gummitrae_hvid_olie",
    "caseId": "case-003_koekken_gummitrae_hvid_olie",
    "category": "bordplade",
    "title": "Køkken Gummitræ Hvid Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-003_koekken_gummitrae_hvid_olie/case-003_koekken_before.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-003_koekken_gummitrae_hvid_olie/case-003_koekken_after.jpeg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-003_koekken_gummitrae_hvid_olie/case-003_koekken_after.jpeg",
      "/media/galleries:bordplade:before-after/case-003_koekken_gummitrae_hvid_olie/case-003_koekken_before.jpeg"
    ]
  },
  {
    "id": "bordplade:case-003_valnoed_natur_olie",
    "caseId": "case-003_valnoed_natur_olie",
    "category": "bordplade",
    "title": "Valnød Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:bordplade/case-003_valnoed_natur_olie/before.1.JPG",
    "afterSrc": "/media/cases:bordplade/case-003_valnoed_natur_olie/after.1.jpeg",
    "gallery": [
      "/media/cases:bordplade/case-003_valnoed_natur_olie/after.1.jpeg",
      "/media/cases:bordplade/case-003_valnoed_natur_olie/after.2.jpeg",
      "/media/cases:bordplade/case-003_valnoed_natur_olie/before.1.JPG",
      "/media/cases:bordplade/case-003_valnoed_natur_olie/before.2.jpeg"
    ]
  },
  {
    "id": "bordplade:case-004_egetrae_hvid_olie",
    "caseId": "case-004_egetrae_hvid_olie",
    "category": "bordplade",
    "title": "Egetræ Hvid Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:bordplade/case-004_egetrae_hvid_olie/before.2.JPG",
    "afterSrc": "/media/cases:bordplade/case-004_egetrae_hvid_olie/after.2.JPG",
    "gallery": [
      "/media/cases:bordplade/case-004_egetrae_hvid_olie/after.2.JPG",
      "/media/cases:bordplade/case-004_egetrae_hvid_olie/before.2.JPG"
    ]
  },
  {
    "id": "bordplade:case-004_koekken_egetrae_hvid_olie",
    "caseId": "case-004_koekken_egetrae_hvid_olie",
    "category": "bordplade",
    "title": "Køkken Egetræ Hvid Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-004_koekken_egetrae_hvid_olie/case-004_koekken_before.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-004_koekken_egetrae_hvid_olie/case-004_koekken_after.jpeg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-004_koekken_egetrae_hvid_olie/case-004_koekken_after.jpeg",
      "/media/galleries:bordplade:before-after/case-004_koekken_egetrae_hvid_olie/case-004_koekken_before.jpeg"
    ]
  },
  {
    "id": "bordplade:case-005_egetrae_natur_olie",
    "caseId": "case-005_egetrae_natur_olie",
    "category": "bordplade",
    "title": "Egetræ Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:bordplade/case-005_egetrae_natur_olie/before.1.jpeg",
    "afterSrc": "/media/cases:bordplade/case-005_egetrae_natur_olie/after.1.jpeg",
    "gallery": [
      "/media/cases:bordplade/case-005_egetrae_natur_olie/after.1.jpeg",
      "/media/cases:bordplade/case-005_egetrae_natur_olie/after.2.jpeg",
      "/media/cases:bordplade/case-005_egetrae_natur_olie/before.1.jpeg",
      "/media/cases:bordplade/case-005_egetrae_natur_olie/before.2.jpeg"
    ]
  },
  {
    "id": "bordplade:case-006_gummitrae_hvid_olie",
    "caseId": "case-006_gummitrae_hvid_olie",
    "category": "bordplade",
    "title": "Gummitræ Hvid Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:bordplade/case-006_gummitrae_hvid_olie/before.1.JPG",
    "afterSrc": "/media/cases:bordplade/case-006_gummitrae_hvid_olie/after.1.JPG",
    "gallery": [
      "/media/cases:bordplade/case-006_gummitrae_hvid_olie/after.1.JPG",
      "/media/cases:bordplade/case-006_gummitrae_hvid_olie/after.2.JPG",
      "/media/cases:bordplade/case-006_gummitrae_hvid_olie/after.3.jpeg",
      "/media/cases:bordplade/case-006_gummitrae_hvid_olie/before.1.JPG",
      "/media/cases:bordplade/case-006_gummitrae_hvid_olie/before.2.JPG",
      "/media/cases:bordplade/case-006_gummitrae_hvid_olie/before.3.jpeg"
    ]
  },
  {
    "id": "bordplade:case-006_koekken_valnoed_natur_olie",
    "caseId": "case-006_koekken_valnoed_natur_olie",
    "category": "bordplade",
    "title": "Køkken Valnød Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-006_koekken_valnoed_natur_olie/Before..jpg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-006_koekken_valnoed_natur_olie/after..jpg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-006_koekken_valnoed_natur_olie/after..jpg",
      "/media/galleries:bordplade:before-after/case-006_koekken_valnoed_natur_olie/Before..jpg"
    ]
  },
  {
    "id": "bordplade:case-007_valnoed_natur_olie",
    "caseId": "case-007_valnoed_natur_olie",
    "category": "bordplade",
    "title": "Valnød Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:bordplade/case-007_valnoed_natur_olie/before.1.jpeg",
    "afterSrc": "/media/cases:bordplade/case-007_valnoed_natur_olie/after.1.jpeg",
    "gallery": [
      "/media/cases:bordplade/case-007_valnoed_natur_olie/after.1.jpeg",
      "/media/cases:bordplade/case-007_valnoed_natur_olie/after.2.jpeg",
      "/media/cases:bordplade/case-007_valnoed_natur_olie/after.3.jpeg",
      "/media/cases:bordplade/case-007_valnoed_natur_olie/after.4.jpeg",
      "/media/cases:bordplade/case-007_valnoed_natur_olie/before.1.jpeg",
      "/media/cases:bordplade/case-007_valnoed_natur_olie/before.3.jpeg",
      "/media/cases:bordplade/case-007_valnoed_natur_olie/before.3.JPG",
      "/media/cases:bordplade/case-007_valnoed_natur_olie/before2.jpeg",
      "/media/cases:bordplade/case-007_valnoed_natur_olie/detail.jpeg"
    ]
  },
  {
    "id": "bordplade:case-008_koekken_ask_hvid_olie",
    "caseId": "case-008_koekken_ask_hvid_olie",
    "category": "bordplade",
    "title": "Køkken Ask Hvid Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-008_koekken_ask_hvid_olie/before..jpg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-008_koekken_ask_hvid_olie/after..jpg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-008_koekken_ask_hvid_olie/after..jpg",
      "/media/galleries:bordplade:before-after/case-008_koekken_ask_hvid_olie/before..jpg"
    ]
  },
  {
    "id": "bordplade:case-009_spisebord_teak_natur_olie",
    "caseId": "case-009_spisebord_teak_natur_olie",
    "category": "bordplade",
    "title": "Spisebord Teak Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-009_spisebord_teak_natur_olie/before.jpg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-009_spisebord_teak_natur_olie/after.jpg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-009_spisebord_teak_natur_olie/after.jpg",
      "/media/galleries:bordplade:before-after/case-009_spisebord_teak_natur_olie/before.jpg"
    ]
  },
  {
    "id": "bordplade:case-010_koekken_valnoed_natur_olie",
    "caseId": "case-010_koekken_valnoed_natur_olie",
    "category": "bordplade",
    "title": "Køkken Valnød Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-010_koekken_valnoed_natur_olie/before.JPG",
    "afterSrc": "/media/galleries:bordplade:before-after/case-010_koekken_valnoed_natur_olie/after.jpeg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-010_koekken_valnoed_natur_olie/after.jpeg",
      "/media/galleries:bordplade:before-after/case-010_koekken_valnoed_natur_olie/before.JPG"
    ]
  },
  {
    "id": "bordplade:case-011_koekken_mahogni_natur_olie",
    "caseId": "case-011_koekken_mahogni_natur_olie",
    "category": "bordplade",
    "title": "Køkken Mahogni Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:bordplade:before-after/case-011_koekken_mahogni_natur_olie/before.jpeg",
    "afterSrc": "/media/galleries:bordplade:before-after/case-011_koekken_mahogni_natur_olie/after.jpeg",
    "gallery": [
      "/media/galleries:bordplade:before-after/case-011_koekken_mahogni_natur_olie/after.jpeg",
      "/media/galleries:bordplade:before-after/case-011_koekken_mahogni_natur_olie/before.jpeg"
    ]
  },
  {
    "id": "gulvafslibning:case-001_Boldens_Gaard_hvid_saebe",
    "caseId": "case-001_Boldens_Gaard_hvid_saebe",
    "category": "gulvafslibning",
    "title": "Boldens Gård Hvid Sæbe",
    "location": null,
    "frontSrc": "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/7.front.jpg",
    "beforeSrc": null,
    "afterSrc": null,
    "gallery": [
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/1.jpg",
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/2.jpg",
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/3.jpg",
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/4.jpg",
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/5.jpg",
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/6.jpg",
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/7.front.jpg",
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/8.jpg",
      "/media/cases:gulv/case-001_Boldens_Gaard_hvid_saebe/9.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-001_stairs",
    "caseId": "case-001_stairs",
    "category": "gulvafslibning",
    "title": "Stairs",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:gulv:before-after/case-001_stairs/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-001_stairs/after.01.jpg",
    "gallery": [
      "/media/galleries:gulv:before-after/case-001_stairs/after.01.jpg",
      "/media/galleries:gulv:before-after/case-001_stairs/before.01.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-002_dark_wood",
    "caseId": "case-002_dark_wood",
    "category": "gulvafslibning",
    "title": "Dark Wood",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:gulv:before-after/case-002_dark_wood/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-002_dark_wood/after.01.jpg",
    "gallery": [
      "/media/galleries:gulv:before-after/case-002_dark_wood/after.01.jpg",
      "/media/galleries:gulv:before-after/case-002_dark_wood/before.01.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-002_Plankegulv_hvid_lud",
    "caseId": "case-002_Plankegulv_hvid_lud",
    "category": "gulvafslibning",
    "title": "Plankegulv Hvid Lud",
    "location": null,
    "frontSrc": "/media/cases:gulv/case-002_Plankegulv_hvid_lud/front.jpg",
    "beforeSrc": "/media/cases:gulv/case-002_Plankegulv_hvid_lud/before.1.jpg",
    "afterSrc": "/media/cases:gulv/case-002_Plankegulv_hvid_lud/after.1.jpg",
    "gallery": [
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/after.1.jpg",
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/after.2.jpg",
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/after.4.jpg",
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/after.5.jpg",
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/before.1.jpg",
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/before.2.jpg",
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/detail.jpg",
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/front.jpg",
      "/media/cases:gulv/case-002_Plankegulv_hvid_lud/progress.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-003_fyrtrae",
    "caseId": "case-003_fyrtrae",
    "category": "gulvafslibning",
    "title": "Fyrtræ",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:gulv:before-after/case-003_fyrtrae/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-003_fyrtrae/after.01.jpg",
    "gallery": [
      "/media/galleries:gulv:before-after/case-003_fyrtrae/after.01.jpg",
      "/media/galleries:gulv:before-after/case-003_fyrtrae/before.01.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-003_Plankegulv_Hvid_lud",
    "caseId": "case-003_Plankegulv_Hvid_lud",
    "category": "gulvafslibning",
    "title": "Plankegulv Hvid Lud",
    "location": null,
    "frontSrc": "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/after:front.jpg",
    "beforeSrc": "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/before.1.jpg",
    "afterSrc": "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/after:front.jpg",
    "gallery": [
      "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/after:front.jpg",
      "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/before.1.jpg",
      "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/before.2.jpg",
      "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/detail.jpg",
      "/media/cases:gulv/case-003_Plankegulv_Hvid_lud/progress.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-004_fernis",
    "caseId": "case-004_fernis",
    "category": "gulvafslibning",
    "title": "Fernis",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:gulv:before-after/case-004_fernis/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-004_fernis/after.01.jpg",
    "gallery": [
      "/media/galleries:gulv:before-after/case-004_fernis/after.01.jpg",
      "/media/galleries:gulv:before-after/case-004_fernis/before.01.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-004_Sildeben_natur_olie",
    "caseId": "case-004_Sildeben_natur_olie",
    "category": "gulvafslibning",
    "title": "Sildeben Natur Olie",
    "location": null,
    "frontSrc": "/media/cases:gulv/case-004_Sildeben_natur_olie/progress:front.jpg",
    "beforeSrc": "/media/cases:gulv/case-004_Sildeben_natur_olie/before.1.JPG",
    "afterSrc": "/media/cases:gulv/case-004_Sildeben_natur_olie/after.1.jpg",
    "gallery": [
      "/media/cases:gulv/case-004_Sildeben_natur_olie/after.1.jpg",
      "/media/cases:gulv/case-004_Sildeben_natur_olie/after.2.jpg",
      "/media/cases:gulv/case-004_Sildeben_natur_olie/after.3.jpg",
      "/media/cases:gulv/case-004_Sildeben_natur_olie/after.4.jpg",
      "/media/cases:gulv/case-004_Sildeben_natur_olie/before.1.JPG",
      "/media/cases:gulv/case-004_Sildeben_natur_olie/before.2.jpg",
      "/media/cases:gulv/case-004_Sildeben_natur_olie/before.4.jpg",
      "/media/cases:gulv/case-004_Sildeben_natur_olie/before3.jpg",
      "/media/cases:gulv/case-004_Sildeben_natur_olie/progress:front.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-005_fernis_stairs",
    "caseId": "case-005_fernis_stairs",
    "category": "gulvafslibning",
    "title": "Fernis Stairs",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:gulv:before-after/case-005_fernis_stairs/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-005_fernis_stairs/after.01.jpg",
    "gallery": [
      "/media/galleries:gulv:before-after/case-005_fernis_stairs/after.01.jpg",
      "/media/galleries:gulv:before-after/case-005_fernis_stairs/before.01.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-005_Parketgulv_natur_lak",
    "caseId": "case-005_Parketgulv_natur_lak",
    "category": "gulvafslibning",
    "title": "Parketgulv Natur Lak",
    "location": null,
    "frontSrc": "/media/cases:gulv/case-005_Parketgulv_natur_lak/front.jpg",
    "beforeSrc": null,
    "afterSrc": null,
    "gallery": [
      "/media/cases:gulv/case-005_Parketgulv_natur_lak/1.jpg",
      "/media/cases:gulv/case-005_Parketgulv_natur_lak/2.jpg",
      "/media/cases:gulv/case-005_Parketgulv_natur_lak/3.jpg",
      "/media/cases:gulv/case-005_Parketgulv_natur_lak/4.jpg",
      "/media/cases:gulv/case-005_Parketgulv_natur_lak/5.jpg",
      "/media/cases:gulv/case-005_Parketgulv_natur_lak/detail.jpg",
      "/media/cases:gulv/case-005_Parketgulv_natur_lak/front.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-006_old",
    "caseId": "case-006_old",
    "category": "gulvafslibning",
    "title": "Old",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:gulv:before-after/case-006_old/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-006_old/after.01.jpg",
    "gallery": [
      "/media/galleries:gulv:before-after/case-006_old/after.01.jpg",
      "/media/galleries:gulv:before-after/case-006_old/before.01.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-006_Plankegulv_natur_lak",
    "caseId": "case-006_Plankegulv_natur_lak",
    "category": "gulvafslibning",
    "title": "Plankegulv Natur Lak",
    "location": null,
    "frontSrc": "/media/cases:gulv/case-006_Plankegulv_natur_lak/front.jpg",
    "beforeSrc": null,
    "afterSrc": null,
    "gallery": [
      "/media/cases:gulv/case-006_Plankegulv_natur_lak/1.jpg",
      "/media/cases:gulv/case-006_Plankegulv_natur_lak/2.jpg",
      "/media/cases:gulv/case-006_Plankegulv_natur_lak/3.jpg",
      "/media/cases:gulv/case-006_Plankegulv_natur_lak/detail.jpg",
      "/media/cases:gulv/case-006_Plankegulv_natur_lak/front.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-007_fyrtrae",
    "caseId": "case-007_fyrtrae",
    "category": "gulvafslibning",
    "title": "Fyrtræ",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/galleries:gulv:before-after/case-007_fyrtrae/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-007_fyrtrae/after.01.jpg",
    "gallery": [
      "/media/galleries:gulv:before-after/case-007_fyrtrae/after.01.jpg",
      "/media/galleries:gulv:before-after/case-007_fyrtrae/before.01.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-007_Sildeben_Dark_coco_olie",
    "caseId": "case-007_Sildeben_Dark_coco_olie",
    "category": "gulvafslibning",
    "title": "Sildeben Dark Coco Olie",
    "location": null,
    "frontSrc": "/media/cases:gulv/case-007_Sildeben_Dark_coco_olie/front.1.jpg",
    "beforeSrc": null,
    "afterSrc": null,
    "gallery": [
      "/media/cases:gulv/case-007_Sildeben_Dark_coco_olie/2.jpg",
      "/media/cases:gulv/case-007_Sildeben_Dark_coco_olie/3.jpg",
      "/media/cases:gulv/case-007_Sildeben_Dark_coco_olie/4.jpg",
      "/media/cases:gulv/case-007_Sildeben_Dark_coco_olie/5.jpg",
      "/media/cases:gulv/case-007_Sildeben_Dark_coco_olie/6.jpg",
      "/media/cases:gulv/case-007_Sildeben_Dark_coco_olie/7.detail.jpg",
      "/media/cases:gulv/case-007_Sildeben_Dark_coco_olie/front.1.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-008_Plankegulv_natur_lak",
    "caseId": "case-008_Plankegulv_natur_lak",
    "category": "gulvafslibning",
    "title": "Plankegulv Natur Lak",
    "location": null,
    "frontSrc": "/media/cases:gulv/case-008_Plankegulv_natur_lak/4.front.jpg",
    "beforeSrc": null,
    "afterSrc": null,
    "gallery": [
      "/media/cases:gulv/case-008_Plankegulv_natur_lak/1.jpg",
      "/media/cases:gulv/case-008_Plankegulv_natur_lak/2.jpg",
      "/media/cases:gulv/case-008_Plankegulv_natur_lak/3.jpg",
      "/media/cases:gulv/case-008_Plankegulv_natur_lak/4.front.jpg",
      "/media/cases:gulv/case-008_Plankegulv_natur_lak/5.detail.jpg",
      "/media/cases:gulv/case-008_Plankegulv_natur_lak/6.jpg",
      "/media/cases:gulv/case-008_Plankegulv_natur_lak/7.jpg"
    ]
  },
  {
    "id": "gulvafslibning:case-009_Sildeben_natur_olie",
    "caseId": "case-009_Sildeben_natur_olie",
    "category": "gulvafslibning",
    "title": "Sildeben Natur Olie",
    "location": null,
    "frontSrc": null,
    "beforeSrc": null,
    "afterSrc": null,
    "gallery": [
      "/media/cases:gulv/case-009_Sildeben_natur_olie/20230404_173732.jpg",
      "/media/cases:gulv/case-009_Sildeben_natur_olie/20230404_175409.jpg"
    ]
  },
  {
    "id": "gulvbelaegning:case-001_vinyl",
    "caseId": "case-001_vinyl",
    "category": "gulvbelaegning",
    "title": "Vinyl",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:gulvbelaegning/case-001_vinyl/before.01.jpg",
    "afterSrc": "/media/cases:gulvbelaegning/case-001_vinyl/after.01.JPG",
    "gallery": [
      "/media/cases:gulvbelaegning/case-001_vinyl/after.01.JPG",
      "/media/cases:gulvbelaegning/case-001_vinyl/before.01.jpg",
      "/media/cases:gulvbelaegning/case-001_vinyl/before.02.JPG"
    ]
  },
  {
    "id": "gulvbelaegning:case-002_spartel",
    "caseId": "case-002_spartel",
    "category": "gulvbelaegning",
    "title": "Spartel",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:gulvbelaegning/case-002_spartel/before.01.jpg",
    "afterSrc": "/media/cases:gulvbelaegning/case-002_spartel/after.01.jpg",
    "gallery": [
      "/media/cases:gulvbelaegning/case-002_spartel/after.01.jpg",
      "/media/cases:gulvbelaegning/case-002_spartel/before.01.jpg"
    ]
  },
  {
    "id": "gulvbelaegning:case-003_sildeben",
    "caseId": "case-003_sildeben",
    "category": "gulvbelaegning",
    "title": "Sildeben",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:gulvbelaegning/case-003_sildeben/before.01.jpg",
    "afterSrc": "/media/cases:gulvbelaegning/case-003_sildeben/after.01.jpg",
    "gallery": [
      "/media/cases:gulvbelaegning/case-003_sildeben/after.01.jpg",
      "/media/cases:gulvbelaegning/case-003_sildeben/after.02.jpg",
      "/media/cases:gulvbelaegning/case-003_sildeben/after.03.jpg",
      "/media/cases:gulvbelaegning/case-003_sildeben/before.01.jpg",
      "/media/cases:gulvbelaegning/case-003_sildeben/before.02.jpg",
      "/media/cases:gulvbelaegning/case-003_sildeben/detail.JPG"
    ]
  },
  {
    "id": "gulvbelaegning:case-004_sildeben",
    "caseId": "case-004_sildeben",
    "category": "gulvbelaegning",
    "title": "Sildeben",
    "location": null,
    "frontSrc": "/media/cases:gulvbelaegning/case-004_sildeben/after1.front.JPG",
    "beforeSrc": "/media/cases:gulvbelaegning/case-004_sildeben/before.1.JPG",
    "afterSrc": "/media/cases:gulvbelaegning/case-004_sildeben/after.3.jpg",
    "gallery": [
      "/media/cases:gulvbelaegning/case-004_sildeben/after.3.jpg",
      "/media/cases:gulvbelaegning/case-004_sildeben/after.4.jpg",
      "/media/cases:gulvbelaegning/case-004_sildeben/after.5.jpg",
      "/media/cases:gulvbelaegning/case-004_sildeben/after1.front.JPG",
      "/media/cases:gulvbelaegning/case-004_sildeben/after2.jpg",
      "/media/cases:gulvbelaegning/case-004_sildeben/before.1.JPG",
      "/media/cases:gulvbelaegning/case-004_sildeben/process.jpg"
    ]
  },
  {
    "id": "gulvbelaegning:case-005_epoxy",
    "caseId": "case-005_epoxy",
    "category": "gulvbelaegning",
    "title": "Epoxy",
    "location": null,
    "frontSrc": "/media/cases:gulvbelaegning/case-005_epoxy/after.2.front.JPG",
    "beforeSrc": null,
    "afterSrc": "/media/cases:gulvbelaegning/case-005_epoxy/after.1.JPG",
    "gallery": [
      "/media/cases:gulvbelaegning/case-005_epoxy/after.1.JPG",
      "/media/cases:gulvbelaegning/case-005_epoxy/after.2.front.JPG",
      "/media/cases:gulvbelaegning/case-005_epoxy/after.3.JPG",
      "/media/cases:gulvbelaegning/case-005_epoxy/process.1_Spartlet.JPG",
      "/media/cases:gulvbelaegning/case-005_epoxy/process.2_Spartlet.JPG",
      "/media/cases:gulvbelaegning/case-005_epoxy/process.3_Sandet.jpg",
      "/media/cases:gulvbelaegning/case-005_epoxy/process.4.detail_Sandet.JPG",
      "/media/cases:gulvbelaegning/case-005_epoxy/process.5_sandet.jpg",
      "/media/cases:gulvbelaegning/case-005_epoxy/process.6_Maling.jpg"
    ]
  },
  {
    "id": "gulvbelaegning:case-006_sildeben",
    "caseId": "case-006_sildeben",
    "category": "gulvbelaegning",
    "title": "Sildeben",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:gulvbelaegning/case-006_sildeben/before.01.JPG",
    "afterSrc": "/media/cases:gulvbelaegning/case-006_sildeben/after.01.JPG",
    "gallery": [
      "/media/cases:gulvbelaegning/case-006_sildeben/after.01.JPG",
      "/media/cases:gulvbelaegning/case-006_sildeben/after.02.JPG",
      "/media/cases:gulvbelaegning/case-006_sildeben/after.03.JPG",
      "/media/cases:gulvbelaegning/case-006_sildeben/after.04.JPG",
      "/media/cases:gulvbelaegning/case-006_sildeben/after.detail.05.JPG",
      "/media/cases:gulvbelaegning/case-006_sildeben/after.wide.JPG",
      "/media/cases:gulvbelaegning/case-006_sildeben/before.01.JPG",
      "/media/cases:gulvbelaegning/case-006_sildeben/before.02.JPG",
      "/media/cases:gulvbelaegning/case-006_sildeben/before.03.JPG"
    ]
  },
  {
    "id": "gulvbelaegning:case-007_parket",
    "caseId": "case-007_parket",
    "category": "gulvbelaegning",
    "title": "Parket",
    "location": null,
    "frontSrc": null,
    "beforeSrc": "/media/cases:gulvbelaegning/case-007_parket/before.01.JPG",
    "afterSrc": "/media/cases:gulvbelaegning/case-007_parket/after.01.JPG",
    "gallery": [
      "/media/cases:gulvbelaegning/case-007_parket/after.01.JPG",
      "/media/cases:gulvbelaegning/case-007_parket/after.02.JPG",
      "/media/cases:gulvbelaegning/case-007_parket/after.03.JPG",
      "/media/cases:gulvbelaegning/case-007_parket/after.04.JPG",
      "/media/cases:gulvbelaegning/case-007_parket/after.05.JPG",
      "/media/cases:gulvbelaegning/case-007_parket/after.wide.JPG",
      "/media/cases:gulvbelaegning/case-007_parket/before.01.JPG",
      "/media/cases:gulvbelaegning/case-007_parket/before.02.JPG",
      "/media/cases:gulvbelaegning/case-007_parket/before3.JPG"
    ]
  },
  {
    "id": "gulvbelaegning:case-008_sildebensbelægning",
    "caseId": "case-008_sildebensbelægning",
    "category": "gulvbelaegning",
    "title": "Sildebensbelægning",
    "location": null,
    "frontSrc": null,
    "beforeSrc": null,
    "afterSrc": null,
    "gallery": [
      "/media/cases:gulvbelaegning/case-008_sildebensbelægning/1.JPG",
      "/media/cases:gulvbelaegning/case-008_sildebensbelægning/2.JPG",
      "/media/cases:gulvbelaegning/case-008_sildebensbelægning/3.JPG",
      "/media/cases:gulvbelaegning/case-008_sildebensbelægning/5.JPG",
      "/media/cases:gulvbelaegning/case-008_sildebensbelægning/6.JPG",
      "/media/cases:gulvbelaegning/case-008_sildebensbelægning/7.JPG",
      "/media/cases:gulvbelaegning/case-008_sildebensbelægning/8.JPG",
      "/media/cases:gulvbelaegning/case-008_sildebensbelægning/9.JPG"
    ]
  },
  {
    "id": "gulvbelaegning:case-009_sildebensbelægning",
    "caseId": "case-009_sildebensbelægning",
    "category": "gulvbelaegning",
    "title": "Sildebensbelægning",
    "location": null,
    "frontSrc": null,
    "beforeSrc": null,
    "afterSrc": null,
    "gallery": [
      "/media/cases:gulvbelaegning/case-009_sildebensbelægning/1.JPG",
      "/media/cases:gulvbelaegning/case-009_sildebensbelægning/2.JPG",
      "/media/cases:gulvbelaegning/case-009_sildebensbelægning/3.JPG",
      "/media/cases:gulvbelaegning/case-009_sildebensbelægning/4.JPG",
      "/media/cases:gulvbelaegning/case-009_sildebensbelægning/5.JPG",
      "/media/cases:gulvbelaegning/case-009_sildebensbelægning/6.JPG",
      "/media/cases:gulvbelaegning/case-009_sildebensbelægning/7.jpeg"
    ]
  }
];

