/* eslint-disable */
// Auto-generated by scripts/generate-client-logos.mjs
// Do not edit manually.

export const clientLogos = [
  {
    "src": "/media/logos/clients/brdr.price.tivoli.logo.svg",
    "alt": "Brdr Price Tivoli logo"
  },
  {
    "src": "/media/logos/clients/fairway.logo.svg",
    "alt": "Fairway logo"
  },
  {
    "src": "/media/logos/clients/rigshospitalets.patienthotel.logo.svg",
    "alt": "Rigshospitalets Patienthotel logo"
  },
  {
    "src": "/media/logos/clients/sengeloesekro.logo.svg",
    "alt": "Sengeloesekro logo"
  },
  {
    "src": "/media/logos/clients/skatteministeriet.logo.svg",
    "alt": "Skatteministeriet logo"
  },
  {
    "src": "/media/logos/clients/vibenshuset.logo.svg",
    "alt": "Vibenshuset logo"
  }
] as const;

