/* eslint-disable */
// Auto-generated by scripts/generate-media-manifest.mjs
// Do not edit manually.

export type BeforeAfterItem = {
  caseId: string;
  beforeSrc: string;
  afterSrc: string;
};

export const beforeAfterGulv: BeforeAfterItem[] = [
  {
    "caseId": "case-001_stairs",
    "beforeSrc": "/media/galleries:gulv:before-after/case-001_stairs/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-001_stairs/after.01.jpg"
  },
  {
    "caseId": "case-002_dark_wood",
    "beforeSrc": "/media/galleries:gulv:before-after/case-002_dark_wood/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-002_dark_wood/after.01.jpg"
  },
  {
    "caseId": "case-003_fyrtrae",
    "beforeSrc": "/media/galleries:gulv:before-after/case-003_fyrtrae/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-003_fyrtrae/after.01.jpg"
  },
  {
    "caseId": "case-004_fernis",
    "beforeSrc": "/media/galleries:gulv:before-after/case-004_fernis/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-004_fernis/after.01.jpg"
  },
  {
    "caseId": "case-005_fernis_stairs",
    "beforeSrc": "/media/galleries:gulv:before-after/case-005_fernis_stairs/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-005_fernis_stairs/after.01.jpg"
  },
  {
    "caseId": "case-006_old",
    "beforeSrc": "/media/galleries:gulv:before-after/case-006_old/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-006_old/after.01.jpg"
  },
  {
    "caseId": "case-007_fyrtrae",
    "beforeSrc": "/media/galleries:gulv:before-after/case-007_fyrtrae/before.01.jpg",
    "afterSrc": "/media/galleries:gulv:before-after/case-007_fyrtrae/after.01.jpg"
  }
];

export const beforeAfterBordplade: BeforeAfterItem[] = [
  {
    "caseId": "case-006_koekken..",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-006_koekken../before.HEIC",
    "afterSrc": "/media/galleries:bordplade:before-after/case-006_koekken../after.HEIC"
  },
  {
    "caseId": "case-008_koekken",
    "beforeSrc": "/media/galleries:bordplade:before-after/case-008_koekken/before.HEIC",
    "afterSrc": "/media/galleries:bordplade:before-after/case-008_koekken/after.HEIC"
  }
];

export const galleryGulv: string[] = [
  "/media/galleries:gulv:before-after/case-001_stairs/after.01.jpg",
  "/media/galleries:gulv:before-after/case-002_dark_wood/after.01.jpg",
  "/media/galleries:gulv:before-after/case-003_fyrtrae/after.01.jpg",
  "/media/galleries:gulv:before-after/case-004_fernis/after.01.jpg",
  "/media/galleries:gulv:before-after/case-005_fernis_stairs/after.01.jpg",
  "/media/galleries:gulv:before-after/case-006_old/after.01.jpg",
  "/media/galleries:gulv:before-after/case-007_fyrtrae/after.01.jpg"
];

export const galleryBordplade: string[] = [
  "/media/galleries:bordplade:before-after/case-006_koekken../after.HEIC",
  "/media/galleries:bordplade:before-after/case-008_koekken/after.HEIC"
];

